### ISSUE TITLE
Build question

### ISSUE THREAD

**Issue by Austinhs** [Apex-master/Arma-3-External-Radar#1]
You mention "reading guest memory" in the "How it works" section, but in the build for the "Memory RPM/WPM Client"  I don't see anything mentioning how you would read that memory. You also only mention one specific computer with these specs:
OS: Manjaro 21.3 KDE
Kernel: x86_64 Linux 5.18.19
CPU: i5-12600K
GPU: RTX 3070ti
RAM: 16gb

Am I wrong in assuming there is two computers at play here? I actually found your repository when looking at `ArmaCept` and saw you forked it, but it looks like instead of reading the network you are reading memory externally.

Any help would be awesome, I have a web background and very little system level experience, wanted to actually build a similar Radar with `ArmaCept` but it seems you've done it already and would love to tinker with that code if I can set it up correctly

**Comment by Austinhs** [comment]
I just looked at a related video you had linked for GPU passthrough:
https://www.youtube.com/watch?v=QlGx0XvWuag

From this video looks like the expectation is to run Manjaro and then run a Windows VM that will run Arma 3?

**Comment by Austinhs** [comment]
No longer needed -- answered my question. Looks like the trick is to use a VM.

**Comment by Apex-master** [comment]
Adding to this if you are planning on using this on Arma 3 with BE enabled you will need to circumvent BE's VM detections.

You will be required to patch the Linux kernel with rdtscv fixes, then recompile QEMU and EDK2 with necessary patches.

For patching refer to https://gitlab.com/DonnerPartyOf1/kvm-hidden.

Last time I had this setup (around May/June) I also had to enable hyper-v on the guest machine, this did slightly decrease my overall performance (5-10% drop).

Make sure to passthrough an actual hard-drive like you did for the GPU and use it for the guest's storage. 

I recently uploaded one of my XMLs for libvirt, I would recommend you refer to it and use some of the stuff in the `<features>` section for hyper-v performance: https://github.com/Apex-master/Arma-3-External-Radar/blob/main/libvirt.xml.

Pass everything on Pafish and you should be good: https://github.com/a0rtega/pafish

**Comment by Austinhs** [comment]
Awesome, thanks for the tips!

Hopefully I can get everything setup and make some contributions to the web side :)

**Comment by Apex-master** [comment]
No worries!

That would be awesome, I stopped playing arma shortly after developing this so I didn't spend much time on this project, would love to see some contributions!

Good luck and feel free to contact me for anything else.
