### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by Austinhs** [Apex-master/Arma-3-External-Radar#2]
While compiling I ran into this error
```bash
$ make: *** No rule to make target 'sio_socket.o', needed by 'arma_dma'.  Stop.
```
Decided to move all of the `utils` file out into the root dir, and then removed the "utils/" pathing in `game.hpp`.

Now I am left with
```bash
In file included from sio_socket.cpp:3:
sio_client_impl.h:14:10: fatal error: websocketpp/client.hpp: No such file or directory
   14 | #include <websocketpp/client.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:12: sio_socket.o] Error 1
```

I am not super skilled in C++, I noticed `sio_client.cpp` had a namespace of `websocketapp` with a client method so figured maybe that was it. But the more I look at `sio_client_impl.h` the more I feel like its just missing the `websocketapp` dependency  -- or I can just be really off track here and screwed up by moving the utils out of the folder ¯\_(ツ)_/¯

**Comment by Apex-master** [comment]
Looks like websocketpp dependency is not installed or not being found, if you followed the manjaro passthrough tutorial install websocketpp using `pacman -S websocketpp`

Check Makefile file for incorrect paths.

If you need more help put your discord in here.

**Comment by Apex-master** [comment]
Looks like websocketpp dependency is not installed or not being found, if you followed the manjaro passthrough tutorial install websocketpp using `pacman -S websocketpp`

Check Makefile file for incorrect paths.

If you need more help put your discord in here.
