### ISSUE TITLE
VFIO / VM Setup

### ISSUE THREAD

**Issue by Austinhs** [Apex-master/Arma-3-External-Radar#4]
So I went through that pass through tutorial just to realize I actually need to run 2 video cards for it to be work. Which then I started looking at a single card solution I found linked in the comments of that video.

Just curious what you use as from your setup you were also on a single card setup... I didn't finish going through the steps to finish the single card setup cause I just kept going black screen on one of the steps and gave up -- and it's 3am right now sooooooo a problem for another time.

**Comment by Austinhs** [comment]
My Discord is also Diversity#2855 but I'm pretty much never answering it -- I run a NFT project and it's kinda always going off because of it on discord so I rarely check it anymore 😅

+it's great documentation for the next person coming through and giving this a shot here

**Comment by Apex-master** [comment]
Depending on the CPU you have, you can just use integrated onboard graphics, I believe with Intel CPUs ones that end with F don't have integrated graphics, the rest do. Not sure with AMD sadly.

**Comment by Apex-master** [comment]
Also, I'm unable to send you a friend request due to your discord settings.
Apex#3398

**Comment by Austinhs** [comment]
Sent you a friend request,

And ahh I didn't think about you being on a Intel CPU with onboard graphics. Yeah I am running a Ryzen 3900x.
I had an old junker card I used because I needed more HDMI ports for my setup so I will put that back in there and give it a shot again later today.

I am guessing run Manjaro on the junk graphics and then dedicate my good card (2080TI) to the VM?

**Comment by Apex-master** [comment]
Yeah, that setup would work great, make sure to select your junk graphics card as a primary GPU device on your bios.

With you having an AMD CPU you should expect slightly worse performance with Hyper-V compared to Intel CPU's, luckily I believe Hyper-V has had a lot of optimizations recently for AMD. I would recommend you setup CPU pinning. Enabling hugepages might also provide you with a performance increase.

https://mathiashueber.com/performance-tweaks-gaming-on-virtual-machines/
